### ISSUE TITLE
大佬，你的web是怎么和mac程序通信的啊

### ISSUE THREAD

**Issue by su350380433** [hohhoo/VLMax#2]

**Comment by hohhoo** [comment]
VLMapWindow.m, [config.userContentController addScriptMessageHandler:self name:@"JSObject"];
vue 然后调用这个JSObject send方法

**Comment by su350380433** [comment]
谢谢

**Comment by su350380433** [comment]
大佬，有没有想加个 记录的功能啊，比如说保存敲鼓点，拒宅日点等

**Comment by hohhoo** [comment]
后面会加收藏功能
