### ISSUE TITLE
VLMax cannot be opened because of a problem.

### ISSUE THREAD

**Issue by shouey** [hohhoo/VLMax#4]
MacOSX 10.14.

Dyld Error Message:
  Library not loaded: /usr/local/opt/usbmuxd/lib/libusbmuxd.4.dylib
  Referenced from: /Users/~/Desktop/VLMAX/VLMax.app/Contents/Frameworks/iMobileDevice.framework/Versions/A/iMobileDevice
  Reason: image not found

**Comment by hohhoo** [comment]
you must install libimobiledevice, 

```shell
brew install -v --devel --fresh automake autoconf libtool wget libimobiledevice
brew install -v --HEAD --fresh --build-from-source ideviceinstaller
```

**Comment by hohhoo** [comment]
this repo is simulate location for  a China iOS Game(一起来捉妖),
this repo used transformation coordinate don't  friendly to other countries,but you can fix it for your country.
